FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY public/manifest.json /usr/share/nginx/html/manifest.json
COPY public/sw.js /usr/share/nginx/html/sw.js
COPY public/icon-192.png /usr/share/nginx/html/icon-192.png
COPY public/icon-512.png /usr/share/nginx/html/icon-512.png
EXPOSE 80
